### ISSUE TITLE
Get NAN when predict MWEs

### ISSUE THREAD

**Issue by Jun-jie-Huang** [omidrohanian/gappy-mwes#1]
Hello, 
     First of all, I would say it was a very nice repo. But I got some bugs when I'm using it. 
     One of the bugs is that I get NAN `preds` in line https://github.com/omidrohanian/gappy-mwes/blob/a19f8a492b75a163c7d85de6fb6d17f388bee371/train_test.py#L87. So I wonder why is that? And could please tell me the right prediction file format that I should feed to `evaluation_v1.py`?

**Comment by shivaat** [comment]
Hi Jun-jie,
Thanks for your interest in the repo.

- Could you please give me more information on what settings exactly you get NAN for `preds`? Surely, you don't get NAN trying on the provided EN_SAMPLE. Am I right?
- Prediction file format is a conllu-like file, exactly the same as the gold standard file (the `.cupt` file that will be generated in the `result` directory under the folder named with the settings that you are trying).

Please let us know if you still have any problem.

**Comment by Jun-jie-Huang** [comment]
Hi Shiva, 
   Thank you for your reply. The settings I use are as follows,

`    LANG = 'EN_SAMPLE'

    DEVorTEST = 'TEST'

    MODEL = 'model_ELMo_H_combined'

    DEP_ADJACENCY_GCN = True

    POSITION_EMBED = False

    POS = False`

, and I acquire the English ELMo embeddings by the instruction of[ ELMo For Many Langs](https://github.com/HIT-SCIR/ELMoForManyLangs).

I also noticed that when I use the EN_SAMPLE for training and test, the test file `predicted_EN_SAMPLE_model_ELMo_H_combined_system.cupt` got " * " prediction for every word.

**Comment by shivaat** [comment]
Hi Jun-jie,

I suppose you would not have any problem when using the embedding sample that we have provided in the repo. Your problem has something to do with the English ELMo embeddings that you trained. Are you sure that you get ELMo weights for all sentences in the EN_SAMPLE data?
